import { cookies } from "next/headers";
import Client from "./client";

export default async function Home() {
  const cookie =
    "eyJ0eXAiOiJKV1QiLCJraWQiOiJuWTkxZmt2T3lrWmpFTDBTa3R1WGJBWkdGcEJ5LXc1OXFaTWluZDg4SDBVIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL3FhMi5zdGFnaW5nLnVuaWR5LmRlIiwic3ViIjoiM2FlOTExYWMtZTI3MS00MjE5LTgxY2EtZDA2ODBjY2U2N2M4IiwiYXVkIjoiSXJXRWRjQWhOMXlDcGQzZUlubjF0bmRDQ3VBSHA4UVFwV3BiY0xvcV9HOCIsImV4cCI6MTc1MDc1ODA5MCwiaWF0IjoxNzUwNzU3OTcwLCJhdXRoX3RpbWUiOjE3NTA3NTcxMzEsImVtYWlsIjoiZnJhbi56ZWthbkB1bmlkeS5kZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJnaXZlbl9uYW1lIjoiQW5vdGhlciIsImZhbWlseV9uYW1lIjoiWmlkYW5lIDIiLCJuYW1lIjoiQW5vdGhlciBaaWRhbmUgMiIsInVwZGF0ZWRfYXQiOjE3NTA3NTcxMzF9.qyjkfLRroPLqjCXEoXc5Pyx8uHap5arWUFDzCR7vbre9b2ROMyzUhTIZAiTUQ_ogVbyzHuN7LsAgbe5zHYv-kBMI3ve24OyycaZ352SStuI9gR13rwFhRIctwqzxH6lgPaXzVlMjLTO_5Mq505GMkin8ritqR2T9tCIl1r4oAIGzaJ_iw5Oma5HJM4SyQEVejpk4vfFXxqrYMkLHkIGn0x8IOEZVBoF6FbJLNypKi4g91_RF02GeCpYqOny2dfyeMHSNTcIFcqeH8tT07_szb5Reg7KRmZ-f7nah0cUQ7yfa1yMqxdDgVsoCyUHBUxlW9CrQbXRsBILvjT8sxuMrew"; //cookies().get("unidy-auth-token");

  return <Client cookie={cookie} />;
}
